### ISSUE TITLE
Error building moveit on rolling with latest sync

### ISSUE THREAD

**Issue by tylerjw** [PickNikRobotics/generate_parameter_library#144]
```
--- stderr: moveit_core
Traceback (most recent call last):
  File "/opt/ros/humble/bin/generate_parameter_library_cpp", line 33, in <module>
    sys.exit(load_entry_point('generate-parameter-library-py==0.3.6', 'console_scripts', 'generate_parameter_library_cpp')())
  File "/opt/ros/humble/bin/generate_parameter_library_cpp", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
gmake[2]: *** [online_signal_smoothing/CMakeFiles/moveit_butterworth_parameters.dir/build.make:71: online_signal_smoothing/moveit_butterworth_parameters/include/moveit_butterworth_parameters.hpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1768: online_signal_smoothing/CMakeFiles/moveit_butterworth_parameters.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
```

**Comment by tylerjw** [comment]
I've been unable to reproduce this so I'm closing it for now.
